site_name: Machine Learning
theme: readthedocs
# repo_name: gramandha/gramandha-docs
repo_url: https://github.com/gramandha/TKE1686-Machine-Learning
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
nav:
  - Home: index.md
  - Materi:
    - Materi1.md
    - Materi2.md
    - Materi3.md

  - Tugas: 
    - LKM1.md
    - LKM2.md

