site_name: Machine Learning
theme: readthedocs
# repo_name: gramandha/gramandha-docs
repo_url: https://github.com/gramandha/TKE1686-Machine-Learning
plugins:
    - search
    - mermaid2:
      version: 10.0.2


markdown_extensions:
  - pymdownx.superfences:
       custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  # - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - https://unpkg.com/mermaid@10.9.3/dist/mermaid.min.js
nav:
  - Home: index.md
  - Materi:
    - Materi1.md
    - Materi2.md
    - Materi3.md
    - Materi4.md

  - Tugas: 
    - LKM1.md
    - LKM2.md
    - LKM3.md
    - LKM4.md

